---
- hosts: all
  gather_facts: false
  user: testuser1
  become: yes

#  vars:
#      homenet: true
#      ion: true
  vars_prompt:
        prompt: isp
        name: "isp"
        default: homenet
        private: no
        when: Network ISP is undefined
  
  tasks:
      - name: "Homenet GateWay Change"
        replace:
          dest: /opt/ifcfg-br0
          regexp: 'GATEWAY=\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}'
          replace: 'GATEWAY=192.168.0.1'
          backup: yes
        when: isp == "homenet"
      - name: "Homenet DNS Change"
        replace:
          dest: /opt/ifcfg-br0
          regexp: 'DNS1=\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}'
          replace: 'DNS1=192.168.0.1'
          backup: yes
        when: isp == "homenet"
        notify: Network Restart

      - name: "ION GateWay Change"
        replace:
          dest: /opt/ifcfg-br0
          regexp: 'GATEWAY=\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}'
          replace: 'GATEWAY=192.168.0.253'
          backup: yes
        when: isp == "ion"
      - name: "ION DNS Change"
        replace:
          dest: /opt/ifcfg-br0
          regexp: 'DNS1=\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}'
          replace: 'DNS1=192.168.0.253'
          backup: yes
        when: isp == "ion"
        notify: Network Restart

  handlers:
    - name: Network Restart
      service: name=network state=restarted



